---
title: "dev"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(rvest)
library(reactable)
```

A POC for scraping the Rstudio community job board and pulling the table of jobs activity.

*I would like to use SASS to style this app as a dip into that set of tools*

First set base URL then read and format as table. Currently only reads the top 30 posts since the website is set as a crawler. Need to determine how to read more of these entries.

```{r}
webpage <- "https://community.rstudio.com/c/jobs/20"

table <- read_html(webpage) %>% 
  html_table()

table <- table[[1]]

table <-
  table %>% 
  select(Topic, Replies, Views, Activity) %>%
  filter(!grepl("Post Jobs", Topic)) %>% 
  mutate(Topic = gsub("\n.*", "", Topic),
         Keyword = case_when(
           grepl("Shiny", Topic, ignore.case = T) ~ "Shiny",
           grepl("Data Scien.*", Topic, ignore.case = T) ~ "Data Scientist",
           grepl("Analyst", Topic, ignore.case = T) ~ "Analyst",
           grepl("database", Topic, ignore.case = T) ~ "Database",
           grepl("Engineer", Topic, ignore.case = T) ~ "Engineering",
           T ~ "Other")) #%>% 
  # Create inter mediate table here
tbl <- 
  table %>%   
  group_by(Keyword) %>% 
  summarize(Replies = sum(Replies),
            Views = sum(Views),
            Count = n()) %>% 
  arrange(desc(Views)) %>% 
  mutate(`Avg. Views` = round(Views / Count, 1))
```

Create the react table

```{r}
r_table <- function(key) {
  reactable(select(filter(table, Keyword == key), Details = Topic), wrap = T)
}

reactable(
  select(tbl, -Views),
  details = function(index) {
    switch(tbl[[index, "Keyword"]],
           "Other" = r_table("Other"),
           "Shiny" = r_table("Shiny"),
           "Analyst" = r_table("Analyst"),
           "Data Scientist" = r_table("Data Scientist"),
           "Engineering" = r_table("Engineering"),
           "Database" = r_table("Database"))
  },
  highlight = T,
  borderless = T,
  showSortIcon = T,
  theme = reactableTheme(color = "black", 
                         style = list(
                           fontFamily = "-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif"
                           )
                         )
)
```


```{r}
reactable(iris[1:5, ], details = function(index) {
  htmltools::div(
    "Details for row: ", index,
    htmltools::tags$pre(paste(capture.output(iris[index, ]), collapse = "\n"))
  )
})
```

