---
title: "R Notebook"
output: 
  md_document:
runtime: shiny
---

```{r setup}
library(shiny)
library(shinymaterial)
library(shinyjs)
library(sf)
library(dplyr)
library(ggplot2)
library(leaflet)
library(leaflet.providers)

shinyOptions(shiny.autoreload = T)
```

```{r}
ui <- material_page(
    material_side_nav(
      fixed = T,
      material_row(
        material_text_box("park-search", 
                          "Search Parks")
      ),
      material_row(
        material_column(width = 9,
                        material_dropdown("parks", 
                                          "Parks"
                        )),
      ),
      material_row(
        material_column(width = 9,
                        material_dropdown("neigh", 
                                          "Neighborhoods"
                        )),
      )
    ))


server <- function(input, output, session) {}

shinyApp(ui, server)
```


 
 
```{r}
# define user interface
ui <-
  material_page(
    tags$head(
      tags$style(includeCSS("styles.css")),
      useShinyjs()
    ),
    title = "Portland Urban Forestry", include_nav_bar = T,
    
    # Side Bar ----------------------------------------------------------------
    
    material_side_nav(
      fixed = T,
      material_row( #TODO address large margins, make smaller
        material_text_box("park-search", 
                          "Search Parks")
      ),
      material_row(
        material_column(width = 9,
                        material_dropdown("parks", 
                                          "Parks",
                                          choices = park_names, selected = "Select Park"
                        )),
        material_column(width = 3,
                        actionButton("flyPark", "", icon = icon("plane"))
        )
      ),
      #            selectize_mod("sel", "Selectize", park_names, placeholder = "Search for Park"),
      material_row(
        material_column(width = 9,
                        material_dropdown("neigh", 
                                          "Neighborhoods",
                                          choices = c("Select Neighborhood", sort(neigh_names)), selected = "Select Park"
                        )),
        material_column(width = 3,
                        actionButton("flyNeigh", "", icon = icon("plane"))
        )
      ),
      material_row(
        material_column(width = 6,offset = 6,
                        actionButton("flyHome", "Full View", icon = icon("map"))
        )
      )
    ),
    
    # Header Controls ---------------------------------------------------------
    
    material_depth(depth = 2,
                   material_row(id = "treecontrols", title = "", class = "center",
                                material_column(width = 4, offset = 2,
                                                switchInput(inputId = "edible-switch", "", value = F, inline = T, onStatus = "success", size = 'mini'),
                                                disabled(radioButtons("edible", label = "Edible Trees",
                                                                      choices = c("Fruit", "Nut"),
                                                                      inline = T))
                                ),
                                bsTooltip(id = "treecontrols", title = "Edible trees", trigger = "click",
                                          placement = "right", options = list(container = "body")),
                                material_column(width = 4,
                                                switchInput("value-switch", "", value = F, inline = T, size = 'mini', onStatus = "success"),
                                                disabled(radioButtons("value", label = "Tree Value",
                                                                      choiceNames = c("Total", "Per Acre"),
                                                                      choiceValues = c("val", "val_per_acre"),
                                                                      inline = T))
                                )
                   )
    ),
    
    
    # Leaflet Map -------------------------------------------------------------
    # height needs to be set to view window height
    
    leafletOutput("map", width = "100%", height = "70vh"), 
    
    # Floating Card on top of map (not being used)
    material_card(id = "card", title = "Most Valuable Parks", 
                  depth = 3,
                  divider = T,
                  plotOutput("valueParks", width = '100%', height = "20vh")),
    
    
    # Plots Below Map -------------------------------------------------------------------
    
    # create non-map content
    material_row(
      material_column(width = 6,
                      "Small Parks",
                      plotOutput("park-small")
      ),
      material_column(width = 6,
                      "Large Parks",
                      plotOutput("park-large"))
    )
    
    # TODO
    
    # what do I want to show?
    # edible trees, 
    # Map ####
    
    # change map based on total value or value per acre
    
    
    # change map colors based on fruit or nut trees
    # TODO park trees species #### also map 
    # most species
    # Show native or not
    # TODO figure out to show the park trees, maybe on a certain zoom level??
    # popup of DBH, Species, annual benefits
    # 
    # Graphs ########
    # horizontal bar graphs show top five and bottom five
    # scatter showing relationship between park size and number of trees
    # scatter showing relationship between park sizee and value of trees
    # Most prominent species 
    # native versus non-native
    
  )

server <- function(input, output, session) {

}

runApp(ui, server)
```



```{r}
library(scales)  

neigh <- read_sf("tree-map/data/data.gpkg", layer = "neigh")
neigh %>% 
  mutate(MAPLABEL = gsub("Improvement League|Residential League|Neighborhood Network|Foothills League",
                         "",
                         MAPLABEL)) %>% 
  pull(MAPLABEL)

val <- "trees_per_acre"

neigh %>% 
  select(!!sym(val)) %>% 
  arrange(!!sym(val))

plotf <- function(df, val) {
  df %>% 
  as.data.frame() %>% 
  arrange(desc( .data[[val]] )) %>% 
  slice(1:5) %>% 
  mutate(MAPLABEL = factor(MAPLABEL)) %>% 
ggplot() +
   geom_bar(aes(x = reorder(MAPLABEL, !!sym(val)) ,
                y = !!sym(val),
                fill = !!sym(val)),
            stat = "identity") +
  theme_classic() +
  labs(y = "Number of Trees",
       x = element_blank()) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.background = element_rect(fill = '#f7f0d2'),
        plot.background = element_rect(fill = '#f7f0d2')) +
  scale_x_discrete(labels = function(x) gsub("d I", 'd\nI', x)) +
  theme(legend.position = "none")
}

plotf(neigh, "trees_per_acre")
```


```{r}
neigh %>% 
  as.data.frame() %>% 
  arrange(desc( !!sym(val) )) %>% 
  slice(1:5) %>% 
  mutate(MAPLABEL = factor(MAPLABEL)) %>% 
ggplot() +
   geom_bar(aes(x = reorder(MAPLABEL, !!sym(val)) ,
                y = !!sym(val),
                fill = !!sym(val)),
            stat = "identity") +
  theme_classic() +
  labs(y = "Number of Trees",
       x = element_blank()) +
  scale_y_continuous(labels = comma) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        panel.background = element_rect(fill = '#f7f0d2'),
        plot.background = element_rect(fill = '#f7f0d2')) +
  scale_x_discrete(labels = function(x) gsub("d I", 'd\nI', x)) +
  theme(legend.position = "none")
```

# from the ev diffusion model

```{r}
  observe({
    colorBy <- input$varinput
    
    # Set Demographics & Map Display Color to switch input 
    if (input$`demographics-choice` == FALSE){
      counties2 <- counties2.ev
      
      pal <- colorNumeric(
        palette = "Greens",
        domain = c(min(map_data[[colorBy]], map_data_gen[[colorBy]]),
                   max(map_data[[colorBy]], map_data_gen[[colorBy]]))
      )
    } else {
      counties2 <- counties2.gen
      
      pal <- colorNumeric(
        palette = "Blues",
        domain = c(min(map_data[[colorBy]], map_data_gen[[colorBy]]),
                   max(map_data[[colorBy]], map_data_gen[[colorBy]]))
      )
    }
    
    # get pop up information (updated to sf object)
    popup <- paste0(
      "<strong>", counties2[['NAME']], " County", "</strong>", "<br>",
      namer[, colorBy], ": ",
      counties2[[colorBy]]
    )
    
    # update map
    leafletProxy("map_demographics", data = counties2) %>%
      clearShapes() %>%
      addPolygons(stroke = TRUE, opacity = 1, weight = 0.7,
                  smoothFactor = 0.1, color = "gainsboro",
                  fillOpacity = 0.7,
                  fillColor = ~pal(get(colorBy)),
                  popup = popup
      ) %>%
      clearControls() %>% 
      addLegend("bottomright", pal = pal, values = c(min(map_data[[colorBy]], map_data_gen[[colorBy]]),
                                                     max(map_data[[colorBy]], map_data_gen[[colorBy]])),
                title = namer[, colorBy],
                labFormat = labelFormat(prefix = ""),
                opacity = 0.8
      ) %>% 
      addControl(actionButton("helper-demo","?", width = '20px', style = "padding:initial;"), position = "topleft")
```



```{r}
val <- "n_trees"
val <- "trees_per_acre"

pal <- colorQuantile(palette = 'Blues', 
                   domain = neigh[[val]], 
                   n = 5)

l <- leaflet(options = leafletOptions(maxZoom = 20,
                                     minZoom = 10,
                                     zoomControl = F)) %>%
      htmlwidgets::onRender("function(el, x) {
                          L.control.zoom({position: 'topright'}).addTo(this)
                          }") %>% 
      addProviderTiles(providers$CartoDB.Positron, group = "Default") %>%
  #    addProviderTiles(providers$Esri.WorldImagery, group = "Satellite") %>% 
      setView(lng = -122.63,
              lat = 45.54,
              zoom = 10) %>%
      setMaxBounds(lng1 = -122.4,
                   lat1 = 45.4,
                   lng2 = -122.8,
                   lat2 = 45.67)# %>%
                )

    addPolygons(data = neigh, 
                stroke = T
                , weight = 1
                # use get() here
                , fillColor = ~pal(get(val))
                , color = "white"
                , dashArray = "2"
                , fillOpacity = 0.7
                , highlight = highlightOptions(
                  weight = 5
                  , color = "#999"
                  , dashArray = ""
                  , fillOpacity = .7
                  , bringToFront = T)
                #   weight = 5,
                #   color = "#666",
                #   dashArray = "",
                #   fillOpacity = 0.7,
                #   bringToFront = TRUE)
```

