---
title: "Raspberry Pi Temperature Sensor"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r global, include=FALSE}
library(flexdashboard)
library(reticulate)
library(g2r)
library(shiny)
library(lubridate)
library(dplyr)

source("R/g2r.R")
source("R/clean_data.R")

# Required calls an error if not able to load python
# py_install("influxdb", pip = T)
# py_install("python-dotenv", pip = T)
  
use_python(python = "/usr/bin/python3")
source_python("py/influx.py")

# return all data points within allotated time frame
# dat <- get_temperature_data(hours_back = 24*30)
# 
# # pull out first time stamp
# now <- dat[1, ]
# 
# dat <- clean_data(dat, "5 mins")
```

## Inputs {.sidebar}

TODOs 
2) implement future for api call

```{r}
# Some JS to make buttons act like radio buttons, 
# could be useful in styling custom radio buttons
# $('.button').click(function() {
#    $('.button').removeClass('active');
#    $(this).addClass('active');
# });
# shinyWidgets::radioGroupButtons(
#   "time",
#   "Time Frame",
#   selected = 3,
#   size = "xs",
#   direction = "vertical",
#   status = "primary" ,
#   justified = F,
#   choiceNames = c("3H",
#                   "1D",
#                   "1W",
#                   "1M"),
#   choiceValues = c(3,
#                    24,
#                    24 * 7,
#                    24 * 30)
# )
```

Add information on the temp sensor
[How I built this](www/details.Rmd)

## Row {.tabset .tabset-fade}

### Temperature

```{r temp graph}
# Calcualte a stay above time
# renderG2({
#   # React to radio inputs
#   d <- subset(dat, interval >= now[["time"]] - hours(as.numeric(input$time)) )
#   
#   g2plot(d, 'temperature')
# })
```

### Humidity

```{r humidity graph}
# renderG2({
#   # React to radio inputs
#   d <- subset(dat, interval >= now[["time"]] - hours(as.numeric(input$time)))
#   
#   g2plot(d, 'humidity')
# })
```

### Info

I built a temp sensor using a Raspberry Pi and [Adafruit DHT-22](https://www.adafruit.com/product/385) which temperature and humidity records to the Pi with a simple python script.

## Row

### Current Conditions

```{r}
# fluidRow(column(width = 6,
#                 div(
#                   class = "boxxy",
#                   p("Current Temperature"),
#                   h2(class = "boxxy-value",
#                      countup::countup(
#                        now[["temperature"]], options = list(useEasing = T,
#                                                              suffix = " Degrees")
#                      ))
#                 ) # end div
#                 ), # end column
#                 column(width = 6,
#                        div(
#                          class = "boxxy",
#                          p("Relative Humidity"),
#                          h2(class = "boxxy-value",
#                             countup::countup(
#                               now[["humidity"]], options = list(
#                               useEasing = T,
#                               suffix = " %"
#                             )))
#                        ) # end div
#                        ) # end column
# )
```

